### ISSUE TITLE
Develop user stories

### ISSUE THREAD

**Issue by drholmie** [scalableinternetservices/TeamPhelps#2]
Develop user stories/features for our piazza variant. 

Some features from piazza:
- Pin posts, visibility access control
- Ask questions, notes, and make followup comments/questions
- Sidebar for navigation, filters and search bar for questions
- Statistics on questions and participation
- File sharing

Some features we can add:
- Chat rooms for TAs/lecturers to keep communication in one place rather than split between piazza and slack for example.

Please feel free to continue the discussion below on more features or anything missed in the list above. This will eventually evolve into more TODOs in the github project.

**Comment by hitomi-nakayama** [comment]
Here are some stories I have thought of:

- As a student, I can "like" a post or a comment, in order to mark which questions or answers are useful.
- As an instructor or TA, I can view a list of students enrolled, so I can manage class enrollment.
- As an instructor or TA, I can view the statistics for each student's posts and comments, so I can gauge their engagement.
- As a student, I can mark my own question as "answered," so other students and instructions will know that I no longer need help.

**Comment by kimiaf1998** [comment]
> 

I addition,

- As an instructor or TA, I can endorse answers.
- As an instructor or TA or student, I can edit students' posts.

**Comment by ySteinhart1** [comment]
We need to start simpler

- As a user I can create an account
- As a user I can create a class
- As a user, I can enroll in a class
- As a user, I can make a post
- As a user, I can comment on a post
